#!/usr/bin/env python3
"""Step 12 orchestration: process_execute and file-level simulation entry."""

import logging
from pathlib import Path
from typing import Any, Dict, Optional, Union

from gnn.execute.detection import (
    _resolve_render_output_dir,
    find_executable_scripts,
    parse_frameworks_parameter,
)
from gnn.execute.metadata import (
    _execution_detail_key,
    _execution_input_identity,
    _execution_script_identity,
    _load_render_summary_contract,
)
from gnn.execute.processor.envelope import _make_distributed_dispatch_failure_result
from gnn.execute.processor.single import execute_single_script
from gnn.execute.processor.summary import (
    _classify_execute_outcome,
    _init_execution_summary,
    _update_framework_status,
    _write_execution_summaries,
)
from gnn.execute.processor.workers import (
    _coerce_dispatch_retries,
    _coerce_execution_workers,
    _run_scripts_with_local_workers,
)
from gnn.utils.logging_utils import (
    log_step_error,
    log_step_start,
    log_step_success,
    log_step_warning,
)

logger = logging.getLogger(__name__)

logger = logging.getLogger(__name__)


def process_execute(
    target_dir: Path,
    output_dir: Path,
    verbose: bool = False,
    frameworks: str = "all",
    **kwargs: Any,
) -> Union[bool, int]:
    """
    Execute rendered implementations from 11_render_output directory.

    This function searches for executable scripts generated by src/gnn/11_render.py
    and executes them using subprocess, capturing their outputs and results.

    Args:
        target_dir: Directory containing rendered executable scripts (typically 11_render_output)
        output_dir: Directory to save execution results
        verbose: Enable verbose output
        **kwargs: Additional arguments

    Returns:
        True if processing successful, False otherwise
    """
    logger = logging.getLogger("execute")

    try:
        log_step_start(
            logger, "Processing execute - searching for rendered implementations"
        )

        # Phase 1.3: validate frameworks arg before parsing. Rejects non-string
        # input and fully-unknown framework lists early with a clear error.
        try:
            from gnn.utils.runtime_safety.validation_schemas import (
                validate_frameworks_arg,
            )

            frameworks = validate_frameworks_arg(frameworks, context="process_execute")
        except ValueError as _verr:
            log_step_error(logger, f"Invalid frameworks argument: {_verr}")
            return False

        # Parse frameworks parameter
        requested_frameworks = parse_frameworks_parameter(frameworks, logger)
        strict_requested_frameworks = str(frameworks).lower() not in {"all", "lite"}
        logger.info(f"Requested frameworks: {requested_frameworks}")

        results_dir = output_dir
        results_dir.mkdir(parents=True, exist_ok=True)

        execution_benchmark_repeats = max(
            1, int(kwargs.get("execution_benchmark_repeats", 1))
        )
        execution_summary_detail = bool(kwargs.get("execution_summary_detail", False))
        require_render_summary = bool(kwargs.get("require_render_summary", True))

        # Initialize execution results
        execution_results: dict[str, Any] = _init_execution_summary(
            target_dir,
            output_dir,
            execution_benchmark_repeats,
            execution_summary_detail,
        )

        execution_results["run_id"] = kwargs.get("run_id")
        execution_results["configuration"] = {
            "frameworks": sorted(requested_frameworks),
            "strict_requested_frameworks": strict_requested_frameworks,
            "options": {
                key: value
                for key, value in kwargs.items()
                if key not in {"run_id", "logger"}
            },
        }
        execution_results["input_identity"] = _execution_input_identity(target_dir)

        # Look for rendered implementations from render output
        render_output_dir = _resolve_render_output_dir(
            target_dir, kwargs, output_dir=results_dir
        )
        if render_output_dir is not None and render_output_dir != target_dir:
            logger.info(f"Found render output directory: {render_output_dir}")

        if verbose:
            logger.info(f"Searching for executable scripts in: {render_output_dir}")

        if not render_output_dir or not render_output_dir.exists():
            log_step_warning(
                logger, f"Render output directory not found: {render_output_dir}"
            )
            execution_results["skipped_reason"] = "no_render_output"
            execution_results["message"] = "No rendered implementations found"
            if require_render_summary:
                execution_results["missing_render_summary"] = (
                    "render output directory unavailable"
                )
        else:
            # Scope the render contract to the current invocation. The
            # pipeline runs Step 12 once per input folder, so a folder-scoped
            # ``target_dir`` must not re-execute every other folder's scripts.
            # When ``target_dir`` is itself the render-output dir (direct
            # invocation), don't scope.
            scope_target: Optional[Path] = (
                target_dir
                if render_output_dir is not None and render_output_dir != target_dir
                else None
            )
            (
                allowed_render_scripts,
                render_failures,
                unsupported_render_receipts,
            ) = _load_render_summary_contract(
                render_output_dir,
                requested_frameworks,
                logger,
                target_dir=scope_target,
                run_id=kwargs.get("run_id"),
            )
            execution_results["render_failures"] = render_failures
            execution_results["unsupported_render_receipts"] = (
                unsupported_render_receipts
            )

            if allowed_render_scripts is None and require_render_summary:
                log_step_warning(
                    logger,
                    f"Render summary contract not found or invalid: {render_output_dir / 'render_processing_summary.json'}",
                )
                execution_results["missing_render_summary"] = str(
                    render_output_dir / "render_processing_summary.json"
                )
                executable_scripts = []
            else:
                executable_scripts = find_executable_scripts(
                    render_output_dir,
                    verbose,
                    logger,
                    requested_frameworks,
                    allowed_scripts=allowed_render_scripts,
                )

            if allowed_render_scripts is not None:
                before_filter = len(executable_scripts)
                executable_scripts = [
                    script
                    for script in executable_scripts
                    if script["path"].resolve() in allowed_render_scripts
                ]
                found_allowed_scripts = {
                    script["path"].resolve() for script in executable_scripts
                }
                missing_render_scripts = sorted(
                    str(path) for path in allowed_render_scripts - found_allowed_scripts
                )
                execution_results["missing_render_scripts"] = missing_render_scripts
                if missing_render_scripts:
                    logger.error(
                        "Latest render summary references %d requested scripts not discoverable for execution",
                        len(missing_render_scripts),
                    )
                filtered_count = before_filter - len(executable_scripts)
                if filtered_count:
                    logger.info(
                        "Ignoring %d rendered scripts not present in the latest render summary",
                        filtered_count,
                    )
            execution_results["total_scripts_found"] = len(executable_scripts)
            execution_results["requested_frameworks"] = requested_frameworks

            if not executable_scripts:
                log_step_warning(logger, "No executable scripts found in render output")
                execution_results["message"] = "No executable scripts found"
                execution_results["skipped_reason"] = "no_executable_scripts"
            else:
                logger.info(
                    f"Found {len(executable_scripts)} executable scripts to run"
                )

                script_identities = {
                    _execution_detail_key(info): _execution_script_identity(info)
                    for info in executable_scripts
                }
                # Extract args
                timeout = kwargs.get("timeout", 3600)
                is_distributed = kwargs.get("distributed", False)
                execution_workers = _coerce_execution_workers(
                    kwargs.get("execution_workers", 1)
                )
                execution_results["execution_mode"] = (
                    "distributed" if is_distributed else "local"
                )
                execution_results["execution_workers"] = execution_workers
                execution_results["backend"] = (
                    kwargs.get("backend", "ray") if is_distributed else None
                )
                dispatch_max_retries = _coerce_dispatch_retries(
                    kwargs.get("distributed_max_retries", 3)
                )
                execution_results["dispatch_max_retries"] = (
                    dispatch_max_retries if is_distributed else 0
                )
                details: list[Any] = []

                if is_distributed:
                    from gnn.execute.distributed import Dispatcher

                    backend = kwargs.get("backend", "ray")
                    dispatcher = Dispatcher(
                        backend=backend,
                        num_cpus=execution_workers,
                        max_retries=dispatch_max_retries,
                    )

                    def ray_script_runner(info: Any, **kws: Any) -> Any:
                        """Execute a rendered simulation script using Ray for distributed processing."""
                        import logging

                        local_logger = logging.getLogger("execute.worker")
                        local_logger.setLevel(logging.INFO)
                        return execute_single_script(
                            info,
                            kws["results_dir"],
                            kws["verbose"],
                            local_logger,
                            kws["timeout"],
                            execution_benchmark_repeats=kws.get(
                                "execution_benchmark_repeats", 1
                            ),
                        )

                    try:
                        details = dispatcher.run_scripts_parallel(
                            executable_scripts,
                            ray_script_runner,
                            results_dir=results_dir,
                            verbose=verbose,
                            timeout=timeout,
                            execution_benchmark_repeats=execution_benchmark_repeats,
                        )
                        if len(details) != len(executable_scripts):
                            raise RuntimeError(
                                "distributed dispatcher returned "
                                f"{len(details)} results for "
                                f"{len(executable_scripts)} scripts"
                            )
                    except Exception as exc:  # noqa: BLE001
                        logger.error(
                            "Distributed %s dispatch failed for %d scripts: %s",
                            backend,
                            len(executable_scripts),
                            exc,
                        )
                        details = [
                            _make_distributed_dispatch_failure_result(
                                script_info,
                                exc,
                                str(backend),
                                dispatch_max_retries,
                            )
                            for script_info in executable_scripts
                        ]
                    finally:
                        dispatcher.shutdown()
                else:
                    details = _run_scripts_with_local_workers(
                        executable_scripts,
                        results_dir,
                        verbose,
                        logger,
                        timeout,
                        execution_workers,
                        execution_benchmark_repeats,
                    )

                inputs_changed = execution_results[
                    "input_identity"
                ] != _execution_input_identity(target_dir)
                for detail in details:
                    identity = script_identities.get(_execution_detail_key(detail))
                    detail["script_identity"] = identity
                    if inputs_changed or identity != _execution_script_identity(detail):
                        detail.update(
                            success=False,
                            skipped=False,
                            status="failed",
                            error="Input or script changed during execution",
                            error_type="receipt_identity_changed",
                        )
                # Update aggregated results
                _update_framework_status(execution_results, details)

        # Classify the outcome before serialising it. The previous flow wrote
        # ``success: true`` and only afterwards returned False for failures,
        # leaving the durable summary in direct conflict with the API result.
        total_found = execution_results["total_scripts_found"]
        successful = execution_results["successful_executions"]
        failed = execution_results["failed_executions"]
        skipped = execution_results.get("skipped_executions", 0)
        render_failures = execution_results.get("render_failures", [])
        missing_render_scripts = execution_results.get("missing_render_scripts", [])
        missing_render_summary = execution_results.get("missing_render_summary")

        classification = _classify_execute_outcome(
            total_found=total_found,
            successful=successful,
            failed=failed,
            skipped=skipped,
            render_failures=render_failures,
            missing_render_scripts=missing_render_scripts,
            missing_render_summary=missing_render_summary,
            strict_requested_frameworks=strict_requested_frameworks,
            unsupported_receipts=execution_results.get(
                "unsupported_render_receipts", []
            ),
        )
        outcome = classification.outcome
        status = classification.status
        reason = classification.reason
        attempted = classification.attempted

        execution_results["total_scripts"] = total_found
        execution_results["attempted_scripts"] = attempted
        execution_results["success_rate"] = (
            round(successful / attempted * 100, 2) if attempted > 0 else 0.0
        )
        execution_results["success"] = outcome is True
        execution_results["status"] = status
        execution_results["exit_code"] = classification.exit_code
        execution_results["outcome_reason"] = reason

        # Save detailed results to summaries subfolder (slim aggregate +
        # optional full detail file). ``_write_execution_summaries`` merges any
        # prior summary, writes the slim + optional detail artifacts, regenerates
        # the report, and restores full details on ``execution_results``.
        _write_execution_summaries(
            results_dir, execution_results, execution_summary_detail, logger
        )

        if reason == "requested_framework_render_failure":
            failure_preview = "; ".join(
                f"{item['file']}:{item['framework']}" for item in render_failures[:5]
            )
            log_step_error(
                logger,
                f"Execute blocked by requested-framework render failures: {failure_preview}",
            )
        elif reason == "required_render_summary_missing":
            log_step_error(logger, "Execute requires a valid render summary contract")
        elif reason == "rendered_script_missing":
            log_step_error(
                logger,
                "Execute blocked because rendered scripts in the summary were not discoverable",
            )
        elif reason == "no_executable_scripts":
            log_step_warning(logger, "No executable scripts found to run")
        elif reason == "unsupported_render_refusals":
            render_refusals = execution_results.get("unsupported_render_receipts", [])
            refusal_preview = "; ".join(
                f"{item['file']}:{item['framework']}" for item in render_refusals[:5]
            )
            log_step_warning(
                logger,
                f"No executable scripts: renderer refused {len(render_refusals)} "
                f"framework rendering(s) as unsupported: {refusal_preview}",
            )
        elif reason == "requested_framework_execution_incomplete":
            log_step_error(
                logger,
                f"Execute failed for requested frameworks: {successful} succeeded, "
                f"{failed} failed, {skipped} skipped",
            )
        elif reason == "script_execution_failure":
            log_step_error(
                logger,
                f"Execute failed: {successful} succeeded, {failed} failed, {skipped} skipped",
            )
        elif status == "success_with_skips":
            log_step_success(
                logger,
                f"Execute completed: {successful} succeeded, {skipped} skipped",
            )
        elif status == "success_with_render_failures":
            log_step_warning(
                logger,
                f"Execute completed {successful} scripts from the best-effort render subset",
            )
        else:
            log_step_success(logger, "Execute processing completed successfully")

        return outcome

    except Exception as e:
        log_step_error(logger, f"Execute processing failed: {e}")
        return False


def execute_simulation_from_gnn(gnn_file: Path, output_dir: Path) -> Dict[str, Any]:
    """
    Execute simulation from GNN file.

    Args:
        gnn_file: Path to GNN file
        output_dir: Output directory

    Returns:
        Dictionary with execution results
    """
    try:
        logger.info(f"Executing simulation for {gnn_file}")

        from gnn.execute.executor import GNNExecutor

        engine = GNNExecutor()

        # Execute simulation
        result = engine.execute_simulation_from_gnn(gnn_file, output_dir)

        return result

    except Exception as e:
        logger.error(f"Failed to execute simulation for {gnn_file}: {e}")
        return {"success": False, "error": str(e)}

