"""Real GUI 1 text actions survive headless export and native file admission.

These consumers do not instantiate Gradio or invoke synthetic UI callbacks.
"""

import hashlib
import json
import logging
from pathlib import Path

import pytest

from gnn.gui.gui_1 import (
    add_state_space_entry,
    gui_1,
    parse_state_space_from_markdown,
    update_state_space_entry,
)
from gnn.gui.gui_1.markdown import MAX_MARKDOWN_CHARS
from gnn.parsers import GNNParsingSystem
from gnn.parsers.common import DataType
from gnn.schema_validator import GNNParser

pytestmark = [pytest.mark.unit, pytest.mark.fast]


def authored_model() -> str:
    """Use a runnable, shipped source with independent authored sensor values."""
    source = (
        Path(__file__).resolve().parents[2] / "input/gnn_files/discrete/simple_mdp.md"
    ).read_text(encoding="utf-8")
    return source.replace(
        "## InitialParameterization\n",
        "## InitialParameterization\nsensor_added=[-0.25, 0.0, 1.5]\n",
        1,
    )


def save_headless(tmp_path: Path, edited: str) -> Path:
    """Save edited source using the documented public GUI 1 headless entry."""
    target = tmp_path / "input"
    target.mkdir()
    source = target / "authored.md"
    source.write_text(edited, encoding="utf-8")
    source_hash = hashlib.sha256(source.read_bytes()).hexdigest()
    output = tmp_path / "22_gui_output"
    result = gui_1(
        target,
        output,
        logging.getLogger("test_gui1_saved_consumer_410"),
        headless=True,
        open_browser=False,
        export_filename="saved_sensor.md",
    )
    assert result["success"] is True
    assert result["backend"] == "headless"
    saved = output / "saved_sensor.md"
    assert Path(result["output_file"]) == saved
    status = json.loads((output / "gui_1_status.json").read_text(encoding="utf-8"))
    assert status["launched"] is False
    assert status["status"] in {"headless_mode", "fallback_mode"}
    assert Path(status["export_file"]) == saved
    assert saved.read_text(encoding="utf-8") == (
        "<!-- HEADLESS ARTIFACT: Generated by GUI 1 Constructor -->\n" + edited
    )
    assert hashlib.sha256(source.read_bytes()).hexdigest() == source_hash
    return saved


def test_add_state_saved_file_is_admitted_by_both_public_readers(
    tmp_path: Path,
) -> None:
    original = authored_model()
    edited = add_state_space_entry(
        original, "sensor_added", [3], "float", "authored signed and zero sensor"
    )
    assert {
        "name": "sensor_added",
        "dims": [3],
        "type": "float",
        "comment": "authored signed and zero sensor",
    } in parse_state_space_from_markdown(edited)
    saved = save_headless(tmp_path, edited)

    syntax = GNNParser().parse_file(saved)
    registry = GNNParsingSystem().parse_file(saved)
    assert registry.success, registry.errors
    assert "sensor_added" in syntax.variables
    assert syntax.variables["sensor_added"].dimensions == [3]
    assert syntax.variables["sensor_added"].data_type == "float"
    assert syntax.variables["sensor_added"].description == (
        "authored signed and zero sensor"
    )
    sensors = [v for v in registry.model.variables if v.name == "sensor_added"]
    assert len(sensors) == 1
    assert sensors[0].dimensions == [3]
    assert sensors[0].data_type is DataType.FLOAT
    assert sensors[0].description == "authored signed and zero sensor"
    assert syntax.parameters["sensor_added"] == [-0.25, 0.0, 1.5]
    assert {p.name: p.value for p in registry.model.parameters}["sensor_added"] == [
        -0.25,
        0.0,
        1.5,
    ]
    assert "## State Space" not in edited
    assert edited.index("sensor_added[3") < edited.index("## Connections")
    assert (
        edited.split("## Connections", 1)[1] == original.split("## Connections", 1)[1]
    )


def test_renamed_state_saved_file_preserves_values_dimensions_and_comment(
    tmp_path: Path,
) -> None:
    original = authored_model()
    pending = add_state_space_entry(
        original, "pending_sensor", [1], "float", "retained authored description"
    )
    edited = update_state_space_entry(
        pending, "pending_sensor", "sensor_added", [3], "float"
    )
    assert "pending_sensor[" not in edited
    saved = save_headless(tmp_path, edited)
    syntax = GNNParser().parse_file(saved)
    registry = GNNParsingSystem().parse_file(saved)
    assert registry.success, registry.errors
    assert "pending_sensor" not in syntax.variables
    assert syntax.variables["sensor_added"].dimensions == [3]
    assert syntax.variables["sensor_added"].data_type == "float"
    assert syntax.variables["sensor_added"].description == (
        "retained authored description"
    )
    sensors = [v for v in registry.model.variables if v.name == "sensor_added"]
    assert len(sensors) == 1
    assert sensors[0].dimensions == [3]
    assert sensors[0].data_type is DataType.FLOAT
    assert sensors[0].description == "retained authored description"
    assert syntax.parameters["sensor_added"] == [-0.25, 0.0, 1.5]
    assert {p.name: p.value for p in registry.model.parameters}["sensor_added"] == [
        -0.25,
        0.0,
        1.5,
    ]


@pytest.mark.parametrize("newline", ["\n", "\r\n", "\r"])
@pytest.mark.parametrize("operation", ["add", "update_missing"])
def test_insertion_preserves_manual_outside_section_bytes(
    newline: str, operation: str
) -> None:
    prefix = newline.join(
        ["# Authored café model  ", "", "## StateSpaceBlock", "s[2,type=float]  ", ""]
    )
    suffix = newline.join(
        ["## InitialParameterization", "s=[-0.25, 0.0]", "## Footer", "manual tail  "]
    )
    source = prefix + suffix
    if operation == "add":
        edited = add_state_space_entry(source, "new_sensor", [2, 3], "float", "kept")
    else:
        edited = update_state_space_entry(
            source, "absent_sensor", "new_sensor", [2, 3], "float", "kept"
        )
    insertion = "new_sensor[2, 3, type=float]  # kept" + newline
    assert edited.encode("utf-8") == (prefix + insertion + suffix).encode("utf-8")
    assert parse_state_space_from_markdown(edited) == [
        {"name": "s", "dims": [2], "type": "float"},
        {"name": "new_sensor", "dims": [2, 3], "type": "float", "comment": "kept"},
    ]


@pytest.mark.parametrize(
    "heading", ["## State Space", "State Space", "## State Space Block"]
)
def test_legacy_spaced_editor_heading_keeps_following_sections(heading: str) -> None:
    prefix = "# Manual legacy document\n" + heading + "\ns[2,type=float]\n"
    suffix = "## Footer\nhandwritten content without final newline"
    source = prefix + suffix
    edited = add_state_space_entry(source, "extra", [4], "int", "legacy")
    assert edited == prefix + "extra[4, type=int]  # legacy\n" + suffix
    assert parse_state_space_from_markdown(edited) == [
        {"name": "s", "dims": [2], "type": "float"},
        {"name": "extra", "dims": [4], "type": "int", "comment": "legacy"},
    ]


def test_duplicate_physical_state_declarations_survive_saved_file(
    tmp_path: Path,
) -> None:
    original = authored_model()
    once = add_state_space_entry(original, "sensor_added", [2], "float", "first")
    twice = add_state_space_entry(once, "sensor_added", [3], "float", "second")
    saved = save_headless(tmp_path, twice)
    registry = GNNParsingSystem().parse_file(saved)
    assert registry.success, registry.errors
    sensors = [v for v in registry.model.variables if v.name == "sensor_added"]
    assert [(v.dimensions, v.data_type, v.description) for v in sensors] == [
        ([2], DataType.FLOAT, "first"),
        ([3], DataType.FLOAT, "second"),
    ]
    # The syntax reader's existing mapping policy keeps the last declaration.
    syntax = GNNParser().parse_file(saved)
    assert syntax.variables["sensor_added"].dimensions == [3]
    assert syntax.variables["sensor_added"].description == "second"
    assert (
        len(
            [
                v
                for v in parse_state_space_from_markdown(twice)
                if v["name"] == "sensor_added"
            ]
        )
        == 2
    )
    assert twice.count("## StateSpaceBlock") == 1
    assert "## State Space" not in twice


def test_add_refuses_oversize_input_without_replacing_prior_saved_model(
    tmp_path: Path,
) -> None:
    original = authored_model()
    saved = save_headless(tmp_path, original)
    before = saved.read_bytes()
    oversized = original + ("x" * MAX_MARKDOWN_CHARS)
    with pytest.raises(ValueError, match="8,388,608-character editor limit"):
        add_state_space_entry(oversized, "sensor_added", [3], "float")
    assert saved.read_bytes() == before
    assert "sensor_added" not in GNNParser().parse_file(saved).variables
