"""Deterministic Julia emission for the validated GraphSpec interchange."""

from __future__ import annotations

import logging
import re
from typing import Final

from .graphspec import (
    GraphSpec,
)

logger = logging.getLogger(__name__)


_JULIA_RESERVED: Final[frozenset[str]] = frozenset(
    {
        "abstract",
        "as",
        "baremodule",
        "begin",
        "break",
        "catch",
        "const",
        "continue",
        "do",
        "else",
        "elseif",
        "end",
        "export",
        "false",
        "finally",
        "for",
        "function",
        "global",
        "if",
        "import",
        "in",
        "let",
        "local",
        "macro",
        "module",
        "mutable",
        "new",
        "primitive",
        "quote",
        "return",
        "struct",
        "true",
        "try",
        "type",
        "using",
        "where",
        "while",
    }
)


def _julia_ident(key: str, taken: set[str], context: str) -> str:
    """Map a GraphSpec key to a unique Julia identifier (deterministic)."""
    ident = key.replace("-", "_")
    if ident in _JULIA_RESERVED or ident.startswith("_"):
        ident = f"x_{ident}"
    if ident in taken:
        raise ValueError(
            f"emit_rxinfer_jl {context}: keys {key!r} collide on the Julia "
            f"identifier {ident!r} after sanitization"
        )
    taken.add(ident)
    return ident


def emit_rxinfer_jl(spec: GraphSpec, model_name: str = "gnn_bayesnet") -> str:
    """Emit a standalone deterministic RxInfer.jl script for ``spec``.

    The script contains one ``@model`` function with one
    ``Categorical``/``DiscreteTransition`` factor per CPT (Dirichlet
    priors in a learning variant), a fail-closed GraphSpec loader,
    evidence conditioning via per-variable observation interfaces
    (``e_<key> ~ DiscreteTransition(<key>, EYE_<key>)``): every latent stays
    free (its marginal is returned); observed ``e_<key>`` interfaces are
    clamped through ``data`` with a one-hot, unobserved ones are supplied as
    ``predictvars``/``missing`` (GraphPPL requires each ``@model`` argument
    to be supplied exactly once),
    marginal printing in topological order, and an optional posteriors sidecar
    (``--out``). Identical GraphSpec input produces byte-identical output;
    the smoke run in ``examples/rxinfer/README.md`` records the real result.
    """
    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", model_name):
        raise ValueError(
            f"emit_rxinfer_jl: invalid model_name {model_name!r} "
            "(must be a Julia identifier: [A-Za-z_][A-Za-z0-9_]*)"
        )
    order = spec.topological_order()
    states_map = spec._states_map()
    parent_map = {key: spec.parents_of(key) for key in order}

    idents: dict[str, str] = {}
    taken: set[str] = set()
    for var in spec.variables:
        idents[var.key] = _julia_ident(var.key, taken, "variable keys")
    model_ident_taken: set[str] = set()
    for key in order:
        _julia_ident(key, model_ident_taken, "model variables")

    lines: list[str] = []
    lines.append("#!/usr/bin/env julia")
    lines.append(
        "# RxInfer.jl Bayes-net inference — generated by gnn.rxinfer_bridge (GNN)."
    )
    lines.append(
        "# GraphSpec format: dafjev.bayesnet/1 (pinned cross-repo contract with daf-jev)."
    )
    lines.append("#")
    lines.append(
        "# Jev integration points (upstream / within / downstream; full story in"
    )
    lines.append("# the module docstring of src/gnn/rxinfer_bridge.py and")
    lines.append("# examples/rxinfer/README.md):")
    lines.append("#   upstream   — CPTs and structure produced by daf-jev elicitation")
    lines.append(
        "#                (propose_structure + elicit_cpts), exchanged as this"
    )
    lines.append("#                GraphSpec JSON")
    lines.append(
        '#   within     — RESERVED: the optional GraphSpec "jev_factors" field'
    )
    lines.append(
        "#                carries Jev-derived factors for future use; this script"
    )
    lines.append(
        f"#                ignores it ({'present' if spec.jev_factors else 'absent'} in this input)"
    )
    lines.append("#   downstream — posteriors printed below; --out FILE writes a")
    lines.append("#                posteriors sidecar JSON for re-asking daf-jev")
    lines.append("#                (see examples/rxinfer/README.md)")
    lines.append("#")
    lines.append("# Usage:")
    lines.append(
        "#   julia --project=. <script>.jl <graphspec.json> [--evidence key=state ...] [--out FILE] [--learn]"
    )
    lines.append("#")
    lines.append(
        "# Deterministic: identical GraphSpec input produces identical script text."
    )
    lines.append("")
    lines.append("using RxInfer")
    lines.append("using JSON")
    lines.append("")
    vars_list = ", ".join(f":{idents[key]}" for key in order)
    lines.append(f"const {model_name.upper()}_VARS = [{vars_list}]")
    lines.append(
        f"const {model_name.upper()}_VARS_SET = Set({model_name.upper()}_VARS)"
    )
    lines.append("const CHILD_PARENTS = Dict{Symbol,Vector{Symbol}}(")
    for key in order:
        parents = ", ".join(f":{idents[p]}" for p in parent_map[key])
        lines.append(f"    :{idents[key]} => Symbol[{parents}],")
    lines.append(")")
    for key in order:
        n_states = len(states_map[key])
        lines.append(
            f"const EYE_{idents[key]} = "
            f"[Float64(i == j) for i in 1:{n_states}, j in 1:{n_states}]"
        )
    raw_to_ident = ", ".join(
        f":{raw} => :{ident}" for raw, ident in sorted(idents.items())
    )
    lines.append(f"const RAW_TO_IDENT = Dict{{Symbol,Symbol}}({raw_to_ident})")
    lines.append(
        "const IDENT_TO_RAW = Dict{Symbol,Symbol}(v => k for (k, v) in RAW_TO_IDENT)"
    )
    lines.append("const LEARNING_ITERATIONS = 25")
    lines.append("const LEARNING_PRIOR_SCALE = 10.0")
    lines.append("const LEARNING_ALPHA_EPS = 1e-6")
    lines.append("")

    lines.append('"""')
    lines.append("    load_spec(path) -> (spec, states, tensors)")
    lines.append("")
    lines.append(
        "Load and validate a dafjev.bayesnet/1 GraphSpec JSON; return the parsed"
    )
    lines.append("spec, the states map (Symbol key -> vector of state labels), and the")
    lines.append(
        "CPT tensors (Symbol child -> Array{Float64} with dims (child, p1, p2, ...))."
    )
    lines.append('"""')
    lines.append("function load_spec(path::AbstractString)")
    lines.append('    isfile(path) || error("GraphSpec file not found: $path")')
    lines.append("    spec = JSON.parsefile(path)")
    lines.append('    got = get(spec, "format", nothing)')
    lines.append(
        '    got == "dafjev.bayesnet/1" || error("GraphSpec format: expected \\"dafjev.bayesnet/1\\", got $got")'
    )
    lines.append("    states = Dict{Symbol,Vector{String}}()")
    lines.append('    for var in get(spec, "variables", [])')
    lines.append('        raw_key = Symbol(String(var["key"]))')
    lines.append(
        '        haskey(RAW_TO_IDENT, raw_key) || error("GraphSpec variables: unknown key $raw_key (not in the compiled model)")'
    )
    lines.append("        key = RAW_TO_IDENT[raw_key]")
    lines.append(
        '        haskey(states, key) && error("GraphSpec variables: duplicate key $key")'
    )
    lines.append('        sts = String.(var["states"])')
    lines.append(
        '        length(sts) >= 2 || error("GraphSpec variable $key: needs at least 2 states")'
    )
    lines.append("        states[key] = sts")
    lines.append("    end")
    lines.append("    for key in " + model_name.upper() + "_VARS")
    lines.append(
        '        haskey(states, key) || error("GraphSpec variables: model variable $key missing")'
    )
    lines.append("    end")
    lines.append("    for key in sort!(collect(keys(states)); by=String)")
    lines.append(
        "        key in "
        + model_name.upper()
        + '_VARS_SET || error("GraphSpec variables: unknown key $key not in the compiled model")'
    )
    lines.append("    end")
    lines.append('    cpts = get(spec, "cpts", nothing)')
    lines.append(
        '    cpts isa AbstractDict || error("GraphSpec cpts: must be an object keyed by child")'
    )
    lines.append("    tensors = Dict{Symbol,Any}()")
    lines.append("    for child in " + model_name.upper() + "_VARS")
    lines.append("        parents = CHILD_PARENTS[child]")
    lines.append("        cpt = get(cpts, String(IDENT_TO_RAW[child]), nothing)")
    lines.append(
        '        cpt === nothing && error("GraphSpec cpts: missing CPT for $child")'
    )
    lines.append('        declared = Symbol.(String.(get(cpt, "parents", [])))')
    lines.append(
        '        Tuple(declared) == Tuple(parents) || error("GraphSpec cpts[$child]: parents must be $(parents), got $(declared)")'
    )
    lines.append('        rows = get(cpt, "rows", nothing)')
    lines.append(
        '        rows isa AbstractVector || error("GraphSpec cpts[$child]: rows must be a list")'
    )
    lines.append("        n_child = length(states[child])")
    lines.append("        if isempty(parents)")
    lines.append(
        '            length(rows) == 1 || error("GraphSpec cpts[$child]: expected exactly 1 prior row")'
    )
    lines.append('            probs = Float64.(rows[1]["probabilities"])')
    lines.append(
        '            length(probs) == n_child || error("GraphSpec cpts[$child]: prior row must have $n_child probabilities")'
    )
    lines.append("            _check_row(child, probs)")
    lines.append("            tensors[child] = probs")
    lines.append("        else")
    lines.append("            expected_rows = prod(length(states[p]) for p in parents)")
    lines.append(
        '            length(rows) == expected_rows || error("GraphSpec cpts[$child]: expected $expected_rows rows, got $(length(rows))")'
    )
    lines.append(
        "            dims = vcat([n_child], [length(states[p]) for p in parents])"
    )
    lines.append("            T = zeros(Float64, dims...)")
    lines.append("            for row in rows")
    lines.append('                assignment = get(row, "assignment", nothing)')
    lines.append(
        '                assignment isa AbstractDict || error("GraphSpec cpts[$child]: row assignment must be an object")'
    )
    lines.append("                idx = Int[]")
    lines.append("                for p in parents")
    lines.append("                    label = String(assignment[String(p)])")
    lines.append("                    i = findfirst(==(label), states[p])")
    lines.append(
        '                    i === nothing && error("GraphSpec cpts[$child]: unknown state $label for parent $p")'
    )
    lines.append("                    push!(idx, i)")
    lines.append("                end")
    lines.append('                probs = Float64.(row["probabilities"])')
    lines.append(
        '                length(probs) == n_child || error("GraphSpec cpts[$child]: row must have $n_child probabilities")'
    )
    lines.append("                _check_row(child, probs)")
    lines.append("                T[:, idx...] = probs")
    lines.append("            end")
    lines.append("            tensors[child] = T")
    lines.append("        end")
    lines.append("    end")
    lines.append("    return spec, states, tensors")
    lines.append("end")
    lines.append("")
    lines.append("function _check_row(child::Symbol, probs::AbstractVector{Float64})")
    lines.append("    for p in probs")
    lines.append(
        '        isfinite(p) && p >= 0.0 || error("GraphSpec cpts[$child]: probability $p is not finite and non-negative")'
    )
    lines.append("    end")
    lines.append(
        '    abs(sum(probs) - 1.0) <= 1e-6 || error("GraphSpec cpts[$child]: probabilities sum to $(sum(probs)), expected 1.0 within 1e-6")'
    )
    lines.append("    return nothing")
    lines.append("end")
    lines.append("")

    # --- main @model -----------------------------------------------------
    arg_names = []
    for key in order:
        arg_names.append(("p_" if not parent_map[key] else "A_") + idents[key])
    e_names = [f"e_{idents[key]}" for key in order]
    lines.append(
        "@model function " + model_name + "(" + ", ".join(arg_names + e_names) + ")"
    )
    for key in order:
        if parent_map[key]:
            cpt_parents = parent_map[key]
            t_args = ", ".join(
                [idents[cpt_parents[0]], f"A_{idents[key]}"]
                + [idents[p] for p in cpt_parents[1:]]
            )
            lines.append(f"    {idents[key]} ~ DiscreteTransition({t_args})")
        else:
            lines.append(f"    {idents[key]} ~ Categorical(p_{idents[key]})")
    for key in order:
        lines.append(
            f"    e_{idents[key]} ~ DiscreteTransition({idents[key]}, EYE_{idents[key]})"
        )
    lines.append("end")
    lines.append("")

    # --- learning variant (Dirichlet priors) ------------------------------
    parented = [key for key in order if parent_map[key]]
    learn_args = []
    for key in order:
        learn_args.append(
            ("alpha_p_" if not parent_map[key] else "alpha_A_") + idents[key]
        )
    lines.append("# --- Learning variant (Dirichlet priors for CPT learning) ---")
    lines.append(
        "# Replace fixed data-arg probabilities with latent Dirichlet priors so"
    )
    lines.append(
        "# RxInfer can learn the CPTs from evidence (pass --learn). Priors use a"
    )
    lines.append(
        "# plain Dirichlet; parented CPTs use DirichletCollection (independent"
    )
    lines.append(
        "# Dirichlets along the FIRST dimension, matching A[child, p1, p2, ...])."
    )
    learn_e_args = [f"e_{idents[key]}" for key in order]
    lines.append(
        "@model function "
        + model_name
        + "_learning("
        + ", ".join(learn_args + learn_e_args)
        + ")"
    )
    for key in order:
        if parent_map[key]:
            cpt_parents = parent_map[key]
            t_args = ", ".join(
                [idents[cpt_parents[0]], f"A_{idents[key]}"]
                + [idents[p] for p in cpt_parents[1:]]
            )
            lines.append(
                f"    A_{idents[key]} ~ DirichletCollection(alpha_A_{idents[key]})"
            )
            lines.append(f"    {idents[key]} ~ DiscreteTransition({t_args})")
        else:
            lines.append(f"    p_{idents[key]} ~ Dirichlet(alpha_p_{idents[key]})")
            lines.append(f"    {idents[key]} ~ Categorical(p_{idents[key]})")
    for key in order:
        lines.append(
            f"    e_{idents[key]} ~ DiscreteTransition({idents[key]}, EYE_{idents[key]})"
        )
    lines.append("end")
    lines.append("")
    if parented:
        lines.append("@constraints function " + model_name + "_learning_constraints()")
        for key in parented:
            lines.append(
                f"    q({idents[key]}, A_{idents[key]}) = q({idents[key]})q(A_{idents[key]})"
            )
        lines.append("end")
        lines.append("")
        init_args = []
        for key in parented:
            init_args.append(f"alpha_A_{idents[key]}")
        for key in order:
            init_args.append(f"uniform_{idents[key]}")
        lines.append(
            "@initialization function "
            + model_name
            + "_learning_init("
            + ", ".join(init_args)
            + ")"
        )
        for key in parented:
            lines.append(
                f"    q(A_{idents[key]}) = DirichletCollection(alpha_A_{idents[key]})"
            )
        for key in order:
            lines.append(f"    q({idents[key]}) = Categorical(uniform_{idents[key]})")
        lines.append("end")
        lines.append("")

    lines.append("@initialization function " + model_name + "_init()")
    for key in order:
        n = len(spec._states_map()[key])
        lines.append(f"    q({idents[key]}) = Categorical(fill(1.0 / {n}, {n}))")
        lines.append(f"    q(e_{idents[key]}) = Categorical(fill(1.0 / {n}, {n}))")
    lines.append("end")
    lines.append("")
    # --- args, evidence, main --------------------------------------------
    lines.append("function parse_args(argv::Vector{String})")
    lines.append(
        '    isempty(argv) && error("usage: julia <script>.jl <graphspec.json> [--evidence key=state ...] [--out FILE] [--learn]")'
    )
    lines.append("    spec_path = argv[1]")
    lines.append("    evidence_labels = Dict{Symbol,String}()")
    lines.append("    out_path = nothing")
    lines.append("    learn = false")
    lines.append("    i = 2")
    lines.append("    while i <= length(argv)")
    lines.append("        arg = argv[i]")
    lines.append('        if arg == "--evidence"')
    lines.append(
        '            i + 1 <= length(argv) || error("--evidence requires a key=state value")'
    )
    lines.append('            kv = split(argv[i+1], "="; limit=2)')
    lines.append(
        '            length(kv) == 2 || error("--evidence expects key=state, got $(argv[i+1])")'
    )
    lines.append("            key = Symbol(strip(kv[1]))")
    lines.append(
        '            haskey(evidence_labels, key) && error("duplicate evidence key: $key")'
    )
    lines.append("            evidence_labels[key] = String(strip(kv[2]))")
    lines.append("            i += 2")
    lines.append('        elseif arg == "--out"')
    lines.append('            i + 1 <= length(argv) || error("--out requires a path")')
    lines.append("            out_path = argv[i+1]")
    lines.append("            i += 2")
    lines.append('        elseif arg == "--learn"')
    lines.append("            learn = true")
    lines.append("            i += 1")
    lines.append("        else")
    lines.append('            error("unknown argument: $arg")')
    lines.append("        end")
    lines.append("    end")
    lines.append("    return spec_path, evidence_labels, out_path, learn")
    lines.append("end")
    lines.append("")
    lines.append("function resolve_evidence(evidence_labels, states)")
    lines.append("    evidence = Dict{Symbol,Any}()")
    lines.append("    for ident in " + model_name.upper() + "_VARS")
    lines.append("        evidence[ident] = missing")
    lines.append("    end")
    lines.append(
        "    for (key, label) in sort!(collect(evidence_labels); by=x->String(x[1]))"
    )
    lines.append(
        '        haskey(RAW_TO_IDENT, key) || error("evidence key not in model: $key")'
    )
    lines.append("        ident = RAW_TO_IDENT[key]")
    lines.append("        options = get(states, ident, nothing)")
    lines.append(
        '        options === nothing && error("evidence key not in model: $key")'
    )
    lines.append("        idx = findfirst(==(label), options)")
    lines.append(
        '        idx === nothing && error("evidence state not in states of $key: $label (states: $options)")'
    )
    lines.append("        onehot = zeros(Float64, length(options))")
    lines.append("        onehot[idx] = 1.0")
    lines.append("        evidence[ident] = onehot")
    lines.append("    end")
    lines.append("    return evidence")
    lines.append("end")
    lines.append("")
    lines.append("function main(argv::Vector{String})")
    lines.append("    spec_path, evidence_labels, out_path, learn = parse_args(argv)")
    lines.append("    spec, states, tensors = load_spec(spec_path)")
    lines.append("    evidence = resolve_evidence(evidence_labels, states)")
    if spec.jev_factors:
        lines.append(
            f"    # jev_factors present in this GraphSpec (RESERVED 'within' "
            f"field): {len(spec.jev_factors)} entries; ignored by this script."
        )
    lines.append("    if learn")
    lines.append("        result = _run_learning(states, tensors, evidence)")
    lines.append("    else")
    lines.append("        result = _run_inference(states, tensors, evidence)")
    lines.append("    end")
    lines.append("    if out_path !== nothing")
    lines.append("        _write_sidecar(result, states, evidence, out_path)")
    lines.append("    end")
    lines.append("    return 0")
    lines.append("end")
    lines.append("")

    model_kwargs = ", ".join(
        f"{arg} = tensors[:{idents[key]}]" for arg, key in zip(arg_names, order)
    )
    lines.append("function _run_inference(states, tensors, evidence::Dict{Symbol,Any})")
    lines.append(
        "    predict = Dict{Symbol,Any}("
        "Symbol(:e_, k) => KeepLast() for (k, v) in evidence if v === missing)"
    )
    lines.append(
        f"    result = infer(model = {model_name}({model_kwargs}), data = Dict{{Symbol,Any}}(Symbol(:e_, k) => v for (k, v) in evidence if v !== missing), predictvars = predict, initialization = {model_name}_init())"
    )
    lines.append('    println("Observed evidence:")')
    lines.append("    for key in " + model_name.upper() + "_VARS")
    lines.append("        evidence[key] === missing && continue")
    lines.append(
        '        println("  $(key) = $(states[key][findfirst(==(1.0), evidence[key])])")'
    )
    lines.append("    end")
    lines.append('    println("Posteriors (marginal P(key)):")')
    lines.append("    for key in " + model_name.upper() + "_VARS")
    lines.append("        evidence[key] !== missing && continue")
    lines.append("        probs = result.posteriors[key].p")
    lines.append(
        '        rendered = join(["$(states[key][i])=$(round(probs[i]; digits=6))" for i in 1:length(probs)], "  ")'
    )
    lines.append('        println("  $(key): $(rendered)")')
    lines.append("    end")
    lines.append("    return result")
    lines.append("end")
    lines.append("")

    lines.append("function _run_learning(states, tensors, evidence::Dict{Symbol,Any})")
    lines.append("    alphas = Dict{Symbol,Any}()")
    lines.append("    for key in " + model_name.upper() + "_VARS")
    lines.append(
        "        alphas[key] = tensors[key] .* LEARNING_PRIOR_SCALE .+ LEARNING_ALPHA_EPS"
    )
    lines.append("    end")
    learn_kwargs = ", ".join(
        f"{arg} = alphas[:{idents[key]}]" for arg, key in zip(learn_args, order)
    )
    if parented:
        learn_init_args = ", ".join(
            [f"alphas[:{idents[key]}]" for key in parented]
            + [
                f"fill(1.0 / length(states[:{idents[key]}]), "
                f"length(states[:{idents[key]}]))"
                for key in order
            ]
        )
        lines.append(
            f"    result = infer(model = {model_name}_learning({learn_kwargs}), "
            "data = Dict{Symbol,Any}(Symbol(:e_, k) => v for (k, v) in evidence), "
            f"constraints = {model_name}_learning_constraints(), initialization = "
            f"{model_name}_learning_init({learn_init_args}), iterations = "
            "LEARNING_ITERATIONS, free_energy = true)"
        )
    else:
        lines.append(
            f"    result = infer(model = {model_name}_learning({learn_kwargs}), "
            "data = Dict{Symbol,Any}(Symbol(:e_, k) => v for (k, v) in evidence), "
            "iterations = LEARNING_ITERATIONS, free_energy = true)"
        )
    lines.append(
        '    println("Learning inference completed (iterations = $(LEARNING_ITERATIONS)).")'
    )
    lines.append('    println("Final variational free energy: $(result.free_energy)")')
    lines.append("    return result")
    lines.append("end")
    lines.append("")

    lines.append(
        "function _write_sidecar(result, states, evidence::Dict{Symbol,Any}, out_path::AbstractString)"
    )
    lines.append("    doc = Dict{String,Any}()")
    lines.append('    doc["format"] = "dafjev.bayesnet-posteriors/1"')
    lines.append(
        '    doc["evidence"] = Dict(String(k) => String(states[k][findfirst(==(1.0), v)]) for (k, v) in evidence if v !== missing)'
    )
    lines.append('    doc["posteriors"] = Dict{String,Any}()')
    lines.append("    for key in " + model_name.upper() + "_VARS")
    lines.append("        if evidence[key] !== missing")
    lines.append("            onehot = evidence[key]")
    lines.append(
        '            doc["posteriors"][String(key)] = Dict(String(states[key][i]) => onehot[i] for i in 1:length(onehot))'
    )
    lines.append("        else")
    lines.append("            probs = result.posteriors[key].p")
    lines.append(
        '            doc["posteriors"][String(key)] = Dict(String(states[key][i]) => probs[i] for i in 1:length(probs))'
    )
    lines.append("        end")
    lines.append("    end")
    lines.append('    open(out_path, "w") do io')
    lines.append("        JSON.print(io, doc, 2)")
    lines.append("    end")
    lines.append('    println("Wrote posteriors sidecar: $out_path")')
    lines.append("    return nothing")
    lines.append("end")
    lines.append("")
    lines.append("if abspath(PROGRAM_FILE) == @__FILE__")
    lines.append("    exit(main(ARGS))")
    lines.append("end")
    lines.append("")
    return "\n".join(lines)
